import {
    ArrowRightLeft,
    ArrowUp,
    Award,
    BarChart3,
    Bell,
    BookOpen,
    Briefcase,
    Building,
    Calendar,
    CheckSquare,
    ClipboardList,
    FileQuestion,
    FileText,
    FolderOpen,
    GraduationCap,
    Home,
    ListTodo,
    Megaphone,
    MessageSquare,
    Search,
    Settings,
    Shield,
    User,
    Users,
    Wrench,
    type LucideIcon
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
    Home,
    FileText,
    BookOpen,
    Settings,
    Users,
    Wrench,
    MessageSquare,
    BarChart3,
    User,
    Calendar,
    CheckSquare,
    Megaphone,
    Briefcase,
    Award,
    ClipboardList,
    FolderOpen,
    ArrowUp,
    ArrowRightLeft,
    Bell,
    Search,
    Shield,
    Building,
    ListTodo,
    GraduationCap,
    FileQuestion
}

export function getIcon(name: string): LucideIcon {
    return iconMap[name] || FileQuestion // Default fallback
}
