services:
  - type: static
    name: prime-hotels-intranet
    buildCommand: bun install && bun run build
    staticPublishDir: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"
