import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

const OPENAI_API_KEY = Deno.env.get('OPENAI_API_KEY')

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
    // Handle CORS
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        const { action, prompt, context } = await req.json()

        // Mock response if no API key or if requested (could add a 'mock' flag)
        // For now, if no key, we return mock data to prevent errors in UI
        if (!OPENAI_API_KEY) {
            console.log('No OpenAI API Key found, returning mock response')
            const mockResult = JSON.stringify([
                {
                    question_text: `Based on '${context?.sop_title || 'content'}': What is the primary purpose?`,
                    question_type: 'mcq',
                    difficulty_level: 'medium',
                    options: [
                        { text: 'To demonstrate AI generation', is_correct: true, feedback: 'Correct!' },
                        { text: 'To show a 404 error', is_correct: false, feedback: 'Wrong.' },
                        { text: 'To fill space', is_correct: false, feedback: 'Incorrect.' }
                    ],
                    correct_answer: 'To demonstrate AI generation',
                    explanation: 'This is a mock question generated because no OpenAI key was configured.',
                    hint: 'Think about why you are seeing this.',
                    tags: ['mock', 'ai']
                },
                {
                    question_text: 'True or False: This question is generated by a mock function.',
                    question_type: 'true_false',
                    difficulty_level: 'easy',
                    correct_answer: 'true',
                    explanation: 'Since the OpenAI key is missing, this local mock function is used.',
                    tags: ['mock', 'debug']
                }
            ])

            return new Response(JSON.stringify({ result: mockResult }), {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            })
        }

        // OpenAI Call
        const response = await fetch('https://api.openai.com/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${OPENAI_API_KEY}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: 'gpt-3.5-turbo',
                messages: [
                    {
                        role: 'system',
                        content: 'You are a helpful assistant that generates JSON-formatted quiz questions based on provided content.'
                    },
                    {
                        role: 'user',
                        content: prompt
                    }
                ],
                temperature: 0.7,
            }),
        })

        const data = await response.json()
        const result = data.choices[0]?.message?.content

        if (!result) {
            throw new Error('No content received from OpenAI')
        }

        return new Response(JSON.stringify({ result }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        })

    } catch (error) {
        return new Response(
            JSON.stringify({ error: error.message }),
            {
                status: 500,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            }
        )
    }
})
