import { PageHeader } from '@/components/layout/PageHeader'
import { LoadingButton } from '@/components/loading'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { useToast } from '@/components/ui/use-toast'
import { ROLES, ROLE_HIERARCHY, STANDARD_JOB_TITLES } from '@/lib/constants'
import { getUserFriendlyError } from '@/lib/errorMessages'
import { supabase } from '@/lib/supabase'
import { userSchema, type UserFormData } from '@/lib/validationSchemas'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useCallback, useEffect, useId, useMemo, useState, type KeyboardEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { ZodError } from 'zod'
import { useTenant } from '@/contexts/TenantContext'
import { appRoleToMembershipRole, membershipToAppRole } from '@/lib/membershipRoles'


import { Badge } from '@/components/ui/badge'
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select"
import {
    Command,
    CommandEmpty,
    CommandGroup,
    CommandInput,
    CommandItem,
    CommandList,
} from "@/components/ui/command"
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover"
import type { Profile } from '@/lib/types'
import type { Database } from '@/types/database.generated'
import { cn, escapeSearchQuery } from "@/lib/utils"
import { ArrowLeft, Building, Check, ChevronsUpDown } from 'lucide-react'

type RoleType = Database['public']['Enums']['app_role']

interface UserFormProps {
  user?: Profile
  initialOrgId?: string
  onClose: () => void
}

interface PotentialManagerRow {
  id: string
  full_name: string
  job_title: string | null
  staff_id: string | null
  organization_memberships?: { role: string | null; department_id: string | null }[]
}

/** Platform roles a profile holds through its memberships. */
const rowRoles = (p: PotentialManagerRow): string[] =>
  (p.organization_memberships ?? []).map((m) => membershipToAppRole(m.role))

const isDepartmentManager = (p: PotentialManagerRow): boolean =>
  (p.organization_memberships ?? []).some((m) => m.role === 'department_manager')

interface PotentialManager {
  id: string
  full_name: string
  job_title: string | null
  staff_id: string | null
  roles: string[]
  isDeptHead: boolean
}

const isValidUUID = (id: string | null | undefined): boolean => {
  if (!id) return false
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
  return uuidRegex.test(id)
}

const MANAGER_ROLES = ['administrator', 'training_manager', 'knowledge_manager']

export function UserForm({ user, initialOrgId, onClose }: UserFormProps) {
  const { currentOrganization, organizations, isPlatformAdmin } = useTenant()
  const { t, i18n } = useTranslation('users')
  const isRTL = i18n.language === 'ar'
  const { t: tCommon } = useTranslation('common')
  const { toast } = useToast()
  const managerListId = useId()

  const [targetOrgId, setTargetOrgId] = useState<string>(
    user?.organization_id || initialOrgId || currentOrganization?.id || organizations[0]?.id || ''
  )
  const [email, setEmail] = useState('')
  const [fullName, setFullName] = useState('')
  const [phone, setPhone] = useState('')
  const [jobTitle, setJobTitle] = useState('')
  const [role, setRole] = useState<RoleType | ''>('')
  const [originalRole, setOriginalRole] = useState<RoleType | ''>('')
  const [isActive, setIsActive] = useState(true)
  const [selectedDepartments, setSelectedDepartments] = useState<string[]>([])
  const [reportingTo, setReportingTo] = useState<string | null>(null)
  const [staffId, setStaffId] = useState('')

  const [openReportingTo, setOpenReportingTo] = useState(false)
  const [managerSearch, setManagerSearch] = useState('')

  const triggerKeyboardAction = (event: KeyboardEvent<HTMLDivElement>, action: () => void) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      event.stopPropagation()
      action()
    }
  }

  // ... (rest of invalidation)

  const createUserMutation = useMutation({
    mutationFn: async () => {
      if (!email || !fullName || !role) {
        throw new Error(t('form.error.required_fields'))
      }

      const finalOrgId = isPlatformAdmin
        ? (targetOrgId || currentOrganization?.id || organizations[0]?.id)
        : currentOrganization?.id

      if (!finalOrgId) {
        throw new Error(t('form.error.select_org', 'Please select a target organization.'))
      }

      // Prepare payload for atomic creation
      // Note: staff_id is auto-generated by database trigger
      const validDepartmentIds = selectedDepartments.filter((id) => isValidUUID(id))
      const payload = {
        email,
        fullName,
        phone: phone || undefined,
        jobTitle: jobTitle || undefined,
        role,
        organizationId: finalOrgId,
        departmentIds: validDepartmentIds,
        reportingTo: reportingTo && isValidUUID(reportingTo) ? reportingTo : undefined,
      }

      // Call the edge function

      const { data, error: fnError } = await supabase.functions.invoke('create-user', {
        body: payload,
      })

      if (fnError) {
        // Extract the real error message from the edge function response body
        let detailedMessage: string | undefined
        const maybeContext = fnError as unknown as { context?: Response | { response?: Response } }
        const response = maybeContext?.context instanceof Response
          ? maybeContext.context
          : maybeContext?.context?.response
        if (response) {
          try {
            const text = await response.text()
            const parsed = text ? (JSON.parse(text) as { error?: string; details?: unknown }) : null
            detailedMessage = parsed?.error || undefined
          } catch {
            // Response body could not be read/parsed — fall through to generic message
          }
        }

        throw new Error(detailedMessage || fnError.message || 'Failed to create user')
      }

      if (data?.error) {
        throw new Error(data.error)
      }

      const response = (data || {}) as { userId?: string, tempPassword?: string, message?: string }
      if (!response.userId) throw new Error('User ID not returned from create-user function')

      return response
    },
    onSuccess: (response) => {
      // Success - refresh the user list

      const tempPwd = response?.tempPassword

      // Copy password to clipboard automatically
      if (tempPwd) {
        navigator.clipboard.writeText(tempPwd).catch(() => {
          toast({
            title: t('form.error.clipboard_failed', 'Copy failed'),
            description: t('form.error.clipboard_failed_desc', 'Please copy the password manually.'),
            variant: "destructive"
          })
        })
      }

      // Show credentials in a persistent toast - NO auto-download needed
      toast({
        title: t('form.success.created_title'),
        description: (
          <div className="mt-2 space-y-2">
            <p><strong>{t('form.email')}:</strong> {email}</p>
            {tempPwd ? (
              <>
                <p><strong>{tCommon('common.password', 'Password')}:</strong> <code className="bg-gray-100 px-2 py-0.5 rounded">{tempPwd}</code></p>
                <p className="text-xs text-gray-500">{t('form.success.password_copied')}</p>
              </>
            ) : (
              <p className="text-xs text-gray-500">{t('form.success.invite_sent', 'Invitation email sent to the user.')}</p>
            )}
          </div>
        ),
        duration: 30000,
      })

      onClose()
    },
    onError: (error) => {
      const errorDetails = getUserFriendlyError(error)
      toast({
        title: t('form.error.create_failed'),
        description: errorDetails.message,
        variant: "destructive"
      })
    }
  })


  const effectiveOrgId = user?.organization_id || targetOrgId || currentOrganization?.id
  /*
    Fetch departments directly scoped to the effective organization
  */
  const { data: departments = [], isLoading: departmentsLoading } = useQuery({
    queryKey: ['admin-departments', effectiveOrgId],
    queryFn: async () => {
      let query = supabase
        .from('departments')
        .select('id, name, name_ar, organization_id')
        .eq('is_active', true)
        .order('name')

      if (effectiveOrgId) {
        query = query.eq('organization_id', effectiveOrgId)
      }

      const { data, error } = await query
      if (error) throw error
      return data ?? []
    },
    enabled: !!effectiveOrgId
  })

  // Standard Job Titles (lookup table was unified into free-text profile column)
  const jobTitlesList = useMemo(() => {
    return STANDARD_JOB_TITLES.map(item => ({
      id: item.id,
      title: isRTL ? item.title_ar : item.title,
      raw_title: item.title,
      default_role: item.default_role,
      category: isRTL ? item.category_ar : item.category,
      department: undefined as { id: string } | undefined
    }))
  }, [isRTL])
  const jobTitlesLoading = false
  const [openJobTitle, setOpenJobTitle] = useState(false)
  const jobTitleListId = useId()

  // Fetch potential managers based on the selected departments
  const { data: potentialManagers } = useQuery({
    queryKey: ['potential-managers', selectedDepartments],
    queryFn: async () => {
      if (selectedDepartments.length === 0) return []

      // Fetch profiles with manager-level roles in the selected departments
      const query = supabase
        .from('profiles')
        .select(`
          id,
          full_name,
          job_title,
          staff_id,
          organization_memberships(role, department_id)
        `)
        .eq('is_active', true)

      const { data, error } = await query
      if (error) throw error

      // Filter to only include people with management roles
      const rows = (data || []) as PotentialManagerRow[]

      return rows
        .filter((p: PotentialManagerRow) => {
          const roles = rowRoles(p)
          const hasManagerRole = isDepartmentManager(p) || roles.some((r: string) => MANAGER_ROLES.includes(r))
          if (!hasManagerRole) return false

          // Only managers in one of the selected departments
          const deptIds = p.organization_memberships?.map((m) => m.department_id).filter(Boolean) || []
          return selectedDepartments.some(d => deptIds.includes(d))
        })
        .map((p: PotentialManagerRow): PotentialManager => ({
          id: p.id,
          full_name: p.full_name,
          job_title: p.job_title,
          staff_id: p.staff_id,
          roles: rowRoles(p),
          isDeptHead: isDepartmentManager(p)
        }))
        // Sort: department heads first, then by name
        .sort((a: PotentialManager, b: PotentialManager) => {
          if (a.isDeptHead && !b.isDeptHead) return -1
          if (!a.isDeptHead && b.isDeptHead) return 1
          return a.full_name.localeCompare(b.full_name)
        })
    },
    enabled: selectedDepartments.length > 0
  })

  const { data: reportingToProfile } = useQuery({
    queryKey: ['manager-profile', reportingTo],
    queryFn: async () => {
      if (!reportingTo) return null
      const { data, error } = await supabase
        .from('profiles')
        .select('id, full_name, job_title, staff_id')
        .eq('id', reportingTo)
        .single()
      if (error) throw error
      return data as { id: string; full_name: string; job_title: string | null; staff_id: string | null }
    },
    enabled: !!reportingTo
  })

  const { data: searchedManagers } = useQuery({
    queryKey: ['manager-search', managerSearch],
    queryFn: async () => {
      const trimmed = managerSearch.trim()
      if (trimmed.length < 2) return []

      const escaped = escapeSearchQuery(trimmed)
      const { data, error } = await supabase
        .from('profiles')
        .select(`
          id,
          full_name,
          job_title,
          staff_id,
          organization_memberships(role, department_id)
        `)
        .eq('is_active', true)
        .or(`full_name.ilike.%${escaped}%,staff_id.ilike.%${escaped}%,job_title.ilike.%${escaped}%`)
        .limit(20)

      if (error) throw error

      const rows = (data || []) as PotentialManagerRow[]

      return rows
        .filter((p: PotentialManagerRow) => {
          const roles = rowRoles(p)
          return isDepartmentManager(p) || roles.some((r: string) => MANAGER_ROLES.includes(r))
        })
        .map((p: PotentialManagerRow): PotentialManager => ({
          id: p.id,
          full_name: p.full_name,
          job_title: p.job_title,
          staff_id: p.staff_id,
          roles: rowRoles(p),
          isDeptHead: isDepartmentManager(p)
        }))
        .sort((a: PotentialManager, b: PotentialManager) => a.full_name.localeCompare(b.full_name))
    },
    enabled: managerSearch.trim().length >= 2
  })

  const combinedManagers = useMemo(() => {
    const byId = new Map<string, PotentialManager>()
    ;(potentialManagers || []).forEach((m: PotentialManager) => byId.set(m.id, m))
    ;(searchedManagers || []).forEach((m: PotentialManager) => byId.set(m.id, m))
    if (reportingToProfile && !byId.has(reportingToProfile.id)) {
      byId.set(reportingToProfile.id, {
        id: reportingToProfile.id,
        full_name: reportingToProfile.full_name,
        job_title: reportingToProfile.job_title,
        staff_id: reportingToProfile.staff_id,
        roles: [],
        isDeptHead: false
      })
    }
    return Array.from(byId.values())
  }, [potentialManagers, reportingToProfile, searchedManagers])

  const selectedManager = reportingTo
    ? combinedManagers.find((m) => m.id === reportingTo) || null
    : null

  const loadUserData = useCallback(async () => {
    if (!user) return

    // Role and departments come from the user's memberships.
    const { data: membershipData } = await supabase
      .from('organization_memberships')
      .select('role, organization_id, department_id, is_primary')
      .eq('user_id', user.id)
      .eq('is_active', true)

    const scopedMembership =
      membershipData?.find((m) => m.organization_id === currentOrganization?.id) ??
      membershipData?.find((m) => m.is_primary) ??
      membershipData?.[0]
    if (scopedMembership) {
      const appRole = membershipToAppRole(scopedMembership.role)
      setRole(appRole)
      setOriginalRole(appRole)
    }

    if (membershipData) {
      setSelectedDepartments(
        membershipData
          .map((m: any) => m.department_id)
          .filter((id): id is string => typeof id === 'string' && isValidUUID(id))
      )
    }

    // Load reporting_to
    const { data: profileData } = await supabase
      .from('profiles')
      .select('reporting_to, staff_id')
      .eq('id', user.id)
      .single()

    if (profileData) {
      setReportingTo(profileData.reporting_to)
      setStaffId(profileData.staff_id || '')
    }
  }, [user])

  const hydrateStateFromUser = useCallback((sourceUser: Profile) => {
    setEmail(sourceUser.email)
    setFullName(sourceUser.full_name || '')
    setPhone(sourceUser.phone || '')
    setJobTitle(sourceUser.job_title || '')
    setIsActive(sourceUser.is_active !== false) // Default to true if undefined
    setReportingTo(sourceUser.reporting_to || null)
    setStaffId(sourceUser.staff_id || '')
    if (sourceUser.organization_id) {
      setTargetOrgId(sourceUser.organization_id)
    }
  }, [])

  useEffect(() => {
    if (user) {
      hydrateStateFromUser(user)
      // Load user's roles and departments
      loadUserData()
    }
  }, [user, loadUserData, hydrateStateFromUser])

  // Auto-suggest manager when department changes (for new users)
  const maybeAutoSuggestManager = useCallback((managers: PotentialManager[] | undefined) => {
    if (user || reportingTo) return
    if (!managers || managers.length === 0) return
    const deptHead = managers.find((m) => m.isDeptHead)
    if (!deptHead) return
    setReportingTo(deptHead.id)
    toast({
      title: t('form.manager_auto_selected'),
      description: t('form.manager_auto_selected_desc', { name: deptHead.full_name, jobTitle: deptHead.job_title || 'Manager' }),
    })
  }, [reportingTo, t, toast, user])

  useEffect(() => {
    maybeAutoSuggestManager(potentialManagers as PotentialManager[] | undefined)
  }, [potentialManagers, maybeAutoSuggestManager])

  // Handle job title selection from DB
  const handleJobTitleSelect = (selectedTitle: string) => {
    setJobTitle(selectedTitle)
    setOpenJobTitle(false)

    // Find the corresponding job title object to get the role
    const titleObj = jobTitlesList?.find(t => t.title === selectedTitle)

    if (titleObj) {
      // Auto-select Role
      setRole(titleObj.default_role)

      let targetDeptId: string | undefined = titleObj.department?.id

      // Fallback: If no direct link, try to match by Category Name
      if (!targetDeptId && titleObj.category && departments) {
        const match = departments.find(d => d.name === titleObj.category)
        if (match) {
          targetDeptId = match.id
        }
      }

      // Auto-select the department
      if (targetDeptId) {
        // Add department if not already selected
        if (!selectedDepartments.includes(targetDeptId)) {
          setSelectedDepartments(prev => [...prev, targetDeptId!])
        }

        toast({
          title: t('form.success.auto_assigned'),
          description: t('form.success.auto_assigned_desc'),
        })
      }
    }
  }



  const updateUserMutation = useMutation({
    mutationFn: async () => {
      if (!user) return

      // Update profile with job title, active status, and reporting_to
      // Note: staff_id is NOT updated - it's auto-generated and read-only
      const { error: profileError } = await supabase
        .from('profiles')
        .update({
          full_name: fullName,
          phone: phone || null,
          job_title: jobTitle || null,
          is_active: isActive,
          reporting_to: reportingTo && isValidUUID(reportingTo) ? reportingTo : null,
        })
        .eq('id', user.id)

      if (profileError) throw profileError

      // Roles live on organization_memberships (user_roles is a read-only view).
      const primaryDeptId = selectedDepartments.find((id) => isValidUUID(id)) || null

      const finalOrgId = targetOrgId || user?.organization_id || currentOrganization?.id
      if (finalOrgId) {
        const { error: orgErr } = await supabase
          .from('profiles')
          .update({ organization_id: finalOrgId })
          .eq('id', user.id)
        if (orgErr) throw orgErr

        const { data: existing, error: existingErr } = await supabase
          .from('organization_memberships')
          .select('id, role')
          .eq('user_id', user.id)
          .eq('organization_id', finalOrgId)
          .order('is_primary', { ascending: false })
          .limit(1)
          .maybeSingle()
        if (existingErr) throw existingErr

        // Keep a more specific membership role (e.g. organization_owner)
        // when it already maps to the chosen platform role.
        const membershipRole =
          existing && membershipToAppRole(existing.role) === role
            ? existing.role
            : appRoleToMembershipRole(role)

        const membershipFields = {
          department_id: primaryDeptId,
          role: membershipRole,
          is_active: true,
          is_primary: true,
          updated_at: new Date().toISOString(),
        }

        const { error: membershipErr } = existing
          ? await supabase.from('organization_memberships').update(membershipFields).eq('id', existing.id)
          : await supabase
              .from('organization_memberships')
              .insert({ ...membershipFields, user_id: user.id, organization_id: finalOrgId })
        if (membershipErr) throw membershipErr
      }
    },
    onSuccess: () => {
      toast({
        title: t('form.success.updated_title', { defaultValue: 'User Updated' }),
        description: t('form.success.updated_message', { defaultValue: 'User information has been updated successfully.' })
      })

      if (user && originalRole && role && originalRole !== role) {
        setOriginalRole(role)
      }

      onClose()
    },
    onError: (error) => {
      const errorDetails = getUserFriendlyError(error)
      toast({
        title: t('form.error.update_failed', { defaultValue: 'Update Failed' }),
        description: errorDetails.message,
        variant: 'destructive'
      })
    }
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    // Validate form data
    try {
      const validDepartmentIds = selectedDepartments.filter((id) => isValidUUID(id))
      const validReportingTo = reportingTo && isValidUUID(reportingTo) ? reportingTo : undefined
      const formData: UserFormData = {
        email,
        full_name: fullName,
        phone: phone || undefined,
        job_title: jobTitle || undefined,
        role: role as UserFormData['role'],
        department_ids: validDepartmentIds,
        reporting_to: validReportingTo,
        is_active: isActive,
        hire_date: undefined,
        staff_id: undefined
      }

      // Validate using Zod schema
      userSchema.parse(formData)

      // If validation passes, proceed with mutation
      if (user) {
        updateUserMutation.mutate()
      } else {
        createUserMutation.mutate()
      }
    } catch (error) {
      // Handle validation errors
      if (error instanceof ZodError) {
        const firstIssue = error.issues[0]
        toast({
          title: t('form.error.validation_failed'),
          description: firstIssue?.message || tCommon('errors:validation_error'),
          variant: 'destructive'
        })
        return
      }

      const errorDetails = getUserFriendlyError(error)
      toast({
        title: t('form.error.validation_failed'),
        description: errorDetails.message,
        variant: 'destructive'
      })
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title={user ? t('form.edit_user') : t('form.create_user')}
        actions={
          <Button variant="ghost" onClick={onClose}>
            <ArrowLeft className="w-4 h-4 me-2" />
            {tCommon('common.back')}
          </Button>
        }
      />

      <Card>
        <CardHeader>
          <CardTitle>{t('form.user_info')}</CardTitle>
        </CardHeader>
        <CardContent>
          {/* Organization Scope Section */}
          <div className="mb-6 p-4 rounded-lg border bg-muted/30">
            {isPlatformAdmin && !user ? (
              <div className="space-y-2">
                <Label htmlFor="targetOrg" className="text-sm font-medium flex items-center gap-2">
                  <Building className="w-4 h-4 text-primary" />
                  {t('form.organization_label', 'Target Organization')}
                  <Badge variant="outline" className="text-[10px] uppercase font-semibold text-primary border-primary/30">
                    {tCommon('organization', 'Organization')}
                  </Badge>
                </Label>
                <Select
                  value={targetOrgId}
                  onValueChange={(val) => {
                    setTargetOrgId(val)
                    setSelectedDepartments([])
                  }}
                >
                  <SelectTrigger id="targetOrg" className="bg-background">
                    <SelectValue placeholder={t('form.select_organization', 'Select Organization')} />
                  </SelectTrigger>
                  <SelectContent>
                    {organizations.map((org) => (
                      <SelectItem key={org.id} value={org.id}>
                        {isRTL && (org as any).name_ar ? (org as any).name_ar : org.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <p className="text-xs text-muted-foreground">
                  {t('form.org_create_notice', 'The new user will be provisioned inside this organization.')}
                </p>
              </div>
            ) : (
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Building className="w-4 h-4 text-primary" />
                  <span className="text-sm font-medium">{tCommon('organization', 'Organization')}:</span>
                  <Badge variant="secondary" className="font-semibold text-xs">
                    {(() => {
                      const userOrg = organizations.find((o) => o.id === (user?.organization_id || targetOrgId))
                        || (user as any)?.organizations
                        || currentOrganization
                      return isRTL && userOrg?.name_ar ? userOrg.name_ar : (userOrg?.name || tCommon('organization', 'Organization'))
                    })()}
                  </Badge>
                </div>
                <span className="text-xs text-muted-foreground font-mono">
                  {organizations.find((o) => o.id === (user?.organization_id || targetOrgId))?.slug || currentOrganization?.slug}
                </span>
              </div>
            )}
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="email">{t('form.email')}</Label>
                <Input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  disabled={!!user}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="fullName">{t('form.full_name')}</Label>
                <Input
                  id="fullName"
                  value={fullName}
                  onChange={(e) => setFullName(e.target.value)}
                  required
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="staffId">
                  {t('form.staff_id', 'Staff ID / Employee Code')}
                </Label>
                {user ? (
                  <div className="flex items-center h-10 px-3 rounded-md border bg-muted/50 font-mono text-sm">
                    {staffId || <span className="text-muted-foreground italic">Not assigned</span>}
                  </div>
                ) : (
                  <div className="flex items-center h-10 px-3 rounded-md border border-dashed bg-green-50 text-green-700 text-sm">
                    <span className="me-2">✨</span>
                    {t('form.staff_id_auto', 'Auto-generated on creation')}
                  </div>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="phone">{t('form.phone')}</Label>
                <Input
                  id="phone"
                  type="tel"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="jobTitle">{t('form.job_title')} *</Label>
              <Popover open={openJobTitle} onOpenChange={setOpenJobTitle}>
                <PopoverTrigger asChild>
                  <Button
                    type="button"
                    variant="outline"
                    role="combobox"
                    aria-expanded={openJobTitle}
                    aria-controls={jobTitleListId}
                    className="w-full justify-between font-normal text-start"
                  >
                    {jobTitle || t('form.select_job_title')}
                    <ChevronsUpDown className="ms-2 h-4 w-4 shrink-0 opacity-50" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-[400px] p-0" align="start">
                  <Command>
                    <CommandInput placeholder={t('form.search_job_title')} />
                    <CommandList id={jobTitleListId}>
                      <CommandEmpty>
                        {jobTitlesLoading ? t('form.loading_job_titles', 'Loading job titles...') : t('form.no_job_title')}
                      </CommandEmpty>
                      <CommandGroup>
                        {jobTitlesList?.map((item) => (
                          <CommandItem
                            key={item.id}
                            value={item.title}
                            onSelect={() => {
                              handleJobTitleSelect(item.title)
                            }}
                            className="p-0 data-[disabled]:pointer-events-auto data-[disabled]:opacity-100"
                          >
                            <div
                              className="w-full flex items-center px-2 py-1.5 cursor-pointer"
                              onPointerDown={(e) => {
                                e.preventDefault()
                              }}
                              onClick={(e) => {
                                e.stopPropagation()
                                handleJobTitleSelect(item.title)
                              }}
                              onKeyDown={(e) => triggerKeyboardAction(e, () => handleJobTitleSelect(item.title))}
                              role="button"
                              tabIndex={0}
                              aria-label={t('form.select_job_title')}
                            >
                              <Check
                                className={cn(
                                  "me-2 h-4 w-4",
                                  jobTitle === item.title ? "opacity-100" : "opacity-0"
                                )}
                              />
                              {item.title} <span className="ms-auto text-xs text-muted-foreground">{item.category}</span>
                            </div>
                          </CommandItem>
                        ))}
                      </CommandGroup>
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
              <p className="text-xs text-muted-foreground">
                {t('form.job_title_helper')}
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="role">{t('form.permission_level')} *</Label>
              <select
                id="role"
                value={role}
                onChange={(e) => setRole(e.target.value as RoleType)}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                required
              >
                <option value="">{t('form.select_role')}</option>
                {ROLE_HIERARCHY.map((r) => (
                  <option key={r} value={r}>
                    {tCommon(`roles.${r}`, ROLES[r].label)}
                  </option>
                ))}
              </select>
              <p className="text-xs text-muted-foreground">
                {t('form.role_helper')}
              </p>
            </div>

            {/* User Status Toggle - Only show for existing users */}
            {user && (
              <div className="flex items-center justify-between p-4 border rounded-lg bg-muted/50">
                <div className="space-y-0.5">
                  <Label htmlFor="is-active" className="font-medium">{t('form.account_status')}</Label>
                  <p className="text-sm text-muted-foreground">
                    {isActive
                      ? t('form.status_active_helper')
                      : t('form.status_inactive_helper')}
                  </p>
                </div>
                <Switch
                  id="is-active"
                  checked={isActive}
                  onCheckedChange={setIsActive}
                />
              </div>
            )}

            <div className="space-y-4">
              <Label>{t('form.departments')}</Label>
              <div className="max-h-60 overflow-y-auto border rounded-md p-4 space-y-4">
                {departmentsLoading ? (
                  <p className="text-sm text-muted-foreground text-center py-4">{t('form.loading_departments', 'Loading departments...')}</p>
                ) : departments.length === 0 ? (
                  <p className="text-sm text-muted-foreground text-center py-4">{t('form.no_departments')}</p>
                ) : (
                  <div className="grid grid-cols-2 gap-2">
                    {departments.map((department) => (
                      <label key={department.id} className="flex items-center gap-2 cursor-pointer hover:bg-muted p-1 rounded">
                        <input
                          type="checkbox"
                          className="rounded border-ds-border text-ds-accent focus:ring-ds-accent"
                          checked={selectedDepartments.includes(department.id)}
                          onChange={(e) => {
                            if (e.target.checked) {
                              setSelectedDepartments([...selectedDepartments, department.id])
                            } else {
                              setSelectedDepartments(selectedDepartments.filter((id) => id !== department.id))
                            }
                          }}
                        />
                        <span className="text-sm text-muted-foreground">{department.name}</span>
                      </label>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Reports To (Manager) */}
            <div className="space-y-2">
              <Label htmlFor="reportingTo">{t('form.reports_to')}</Label>
              <Popover open={openReportingTo} onOpenChange={setOpenReportingTo}>
                <PopoverTrigger asChild>
                  <Button
                    type="button"
                    variant="outline"
                    role="combobox"
                    aria-expanded={openReportingTo}
                    aria-controls={managerListId}
                    className="w-full justify-between font-normal text-start"
                  >
                    {reportingTo
                      ? selectedManager?.full_name || reportingToProfile?.full_name || t('form.selected_manager')
                      : t('form.select_manager')}
                    <ChevronsUpDown className="ms-2 h-4 w-4 shrink-0 opacity-50" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-[400px] p-0" align="start">
                  <Command>
                    <CommandInput
                      placeholder={t('form.search_managers')}
                      value={managerSearch}
                      onValueChange={setManagerSearch}
                    />
                    <CommandList id={managerListId}>
                      <CommandEmpty>
                        {managerSearch.trim().length >= 2
                          ? t('form.manager_none_helper')
                          : selectedDepartments.length === 0
                            ? t('form.manager_dept_helper')
                            : t('form.manager_none_helper')
                        }
                      </CommandEmpty>
                      <CommandGroup heading={t('form.available_managers')}>
                        <CommandItem
                          value="no-manager"
                          onSelect={() => {
                            setReportingTo(null)
                            setManagerSearch('')
                            setOpenReportingTo(false)
                          }}
                          className="p-0 data-[disabled]:pointer-events-auto data-[disabled]:opacity-100"
                        >
                          <div
                            className="w-full flex items-center px-2 py-1.5 cursor-pointer"
                            onPointerDown={(e) => e.preventDefault()}
                            onClick={(e) => {
                              e.stopPropagation()
                              setReportingTo(null)
                              setManagerSearch('')
                              setOpenReportingTo(false)
                            }}
                            onKeyDown={(e) => triggerKeyboardAction(e, () => {
                              setReportingTo(null)
                              setManagerSearch('')
                              setOpenReportingTo(false)
                            })}
                            role="button"
                            tabIndex={0}
                            aria-label={t('form.no_manager_top')}
                          >
                            <Check
                              className={cn(
                                "me-2 h-4 w-4",
                                !reportingTo ? "opacity-100" : "opacity-0"
                              )}
                            />
                            <span className="text-muted-foreground">{t('form.no_manager_top')}</span>
                          </div>
                        </CommandItem>
                        {potentialManagers?.map((manager: PotentialManager) => (
                          <CommandItem
                            key={manager.id}
                            value={`${manager.full_name} ${manager.staff_id || ''} ${manager.job_title || ''}`}
                            onSelect={() => {
                              setReportingTo(manager.id)
                              setManagerSearch('')
                              setOpenReportingTo(false)
                            }}
                            className="p-0 data-[disabled]:pointer-events-auto data-[disabled]:opacity-100"
                          >
                            <div
                              className="w-full flex items-center px-2 py-1.5 cursor-pointer"
                              onPointerDown={(e) => e.preventDefault()}
                              onClick={(e) => {
                                e.stopPropagation()
                                setReportingTo(manager.id)
                                setManagerSearch('')
                                setOpenReportingTo(false)
                              }}
                              onKeyDown={(e) => triggerKeyboardAction(e, () => {
                                setReportingTo(manager.id)
                                setManagerSearch('')
                                setOpenReportingTo(false)
                              })}
                              role="button"
                              tabIndex={0}
                              aria-label={t('form.select_manager')}
                            >
                              <Check
                                className={cn(
                                  "me-2 h-4 w-4",
                                  reportingTo === manager.id ? "opacity-100" : "opacity-0"
                                )}
                              />
                              <span>{manager.full_name}</span>
                              <span className="ms-2 text-[10px] bg-slate-100 px-1 rounded text-slate-500 font-mono">
                                {manager.staff_id || 'no-id'}
                              </span>
                              <span className="ms-auto text-xs text-muted-foreground">
                                {manager.job_title || manager.roles?.join(', ')}
                              </span>
                              {manager.isDeptHead && (
                                <span className="ms-2 text-xs bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded">
                                  {t('form.dept_head')}
                                </span>
                              )}
                            </div>
                          </CommandItem>
                        ))}
                      </CommandGroup>
                      {managerSearch.trim().length >= 2 && (searchedManagers?.length || 0) > 0 && (
                        <CommandGroup heading={t('form.search_results', 'Search Results')}>
                          {searchedManagers
                            ?.filter((manager: PotentialManager) => !potentialManagers?.some((m) => m.id === manager.id))
                            .map((manager: PotentialManager) => (
                              <CommandItem
                                key={manager.id}
                                value={`${manager.full_name} ${manager.staff_id || ''} ${manager.job_title || ''}`}
                                onSelect={() => {
                                  setReportingTo(manager.id)
                                  setManagerSearch('')
                                  setOpenReportingTo(false)
                                }}
                                className="p-0 data-[disabled]:pointer-events-auto data-[disabled]:opacity-100"
                              >
                                <div
                                  className="w-full flex items-center px-2 py-1.5 cursor-pointer"
                                  onPointerDown={(e) => e.preventDefault()}
                                  onClick={(e) => {
                                    e.stopPropagation()
                                    setReportingTo(manager.id)
                                    setManagerSearch('')
                                    setOpenReportingTo(false)
                                  }}
                                  onKeyDown={(e) => triggerKeyboardAction(e, () => {
                                    setReportingTo(manager.id)
                                    setManagerSearch('')
                                    setOpenReportingTo(false)
                                  })}
                                  role="button"
                                  tabIndex={0}
                                  aria-label={t('form.select_manager')}
                                >
                                  <Check
                                    className={cn(
                                      "me-2 h-4 w-4",
                                      reportingTo === manager.id ? "opacity-100" : "opacity-0"
                                    )}
                                  />
                                  <span>{manager.full_name}</span>
                                  <span className="ms-2 text-[10px] bg-slate-100 px-1 rounded text-slate-500 font-mono">
                                    {manager.staff_id || 'no-id'}
                                  </span>
                                  <span className="ms-auto text-xs text-muted-foreground">
                                    {manager.job_title || manager.roles?.join(', ')}
                                  </span>
                                </div>
                              </CommandItem>
                            ))}
                        </CommandGroup>
                      )}
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
              <p className="text-xs text-muted-foreground">
                {selectedDepartments.length === 0
                  ? t('form.suggested_manager_helper')
                  : reportingTo
                    ? t('form.auto_suggested_helper')
                    : t('form.top_level_helper')}
              </p>
            </div>

            <div className="flex justify-end gap-2">
              <Button type="button" variant="outline" onClick={onClose}>
                {tCommon('common.cancel')}
              </Button>
              <LoadingButton
                type="submit"
                className="bg-ds-accent text-white hover:bg-ds-accent/90 rounded-md transition-colors"
                loading={createUserMutation.isPending || updateUserMutation.isPending}
                loadingText={user ? tCommon('common.updating') : tCommon('common.creating')}
              >
                {user ? tCommon('common.update') : tCommon('common.create')} {t('user')}
              </LoadingButton>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
