import { PageHeader } from '@/components/layout/PageHeader'
import { LoadingButton } from '@/components/loading'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { useToast } from '@/components/ui/use-toast'
import { ROLES, ROLE_HIERARCHY } from '@/lib/constants'
import { getUserFriendlyError } from '@/lib/errorMessages'
import { supabase } from '@/lib/supabase'
import { userSchema, type UserFormData } from '@/lib/validationSchemas'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useCallback, useEffect, useId, useMemo, useState, type KeyboardEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { ZodError } from 'zod'
import { useTenant } from '@/contexts/TenantContext'


import {
    Command,
    CommandEmpty,
    CommandGroup,
    CommandInput,
    CommandItem,
    CommandList,
} from "@/components/ui/command"
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover"
import { useDepartments } from '@/hooks/useDepartments'
import type { AppRole } from '@/lib/constants'
import type { Profile } from '@/lib/types'
import type { Database } from '@/types/database.generated'
import { cn, escapeSearchQuery } from "@/lib/utils"
import { ArrowLeft, Check, ChevronsUpDown } from 'lucide-react'

type RoleType = Database['public']['Enums']['app_role']

interface UserFormProps {
  user?: Profile
  onClose: () => void
}

interface PotentialManagerRow {
  id: string
  full_name: string
  job_title: string | null
  staff_id: string | null
  user_roles?: { role: string }[]
  user_departments?: { department_id: string }[]
  user_properties?: { property_id: string }[]
}

interface PotentialManager {
  id: string
  full_name: string
  job_title: string | null
  staff_id: string | null
  roles: string[]
  isDeptHead: boolean
}

const isValidUUID = (id: string | null | undefined): boolean => {
  if (!id) return false
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
  return uuidRegex.test(id)
}

const MANAGER_ROLES = ['administrator', 'super_admin', 'training_manager', 'knowledge_manager', 'corporate_admin', 'regional_admin', 'regional_hr', 'property_manager', 'property_hr', 'department_head']

export function UserForm({ user, onClose }: UserFormProps) {
  const { currentOrganization } = useTenant()
  const { t } = useTranslation('users')
  const { t: tCommon } = useTranslation('common')
  const { toast } = useToast()
  const managerListId = useId()
  const [email, setEmail] = useState('')
  const [fullName, setFullName] = useState('')
  const [phone, setPhone] = useState('')
  const [jobTitle, setJobTitle] = useState('')
  const [role, setRole] = useState<RoleType | ''>('')
  const [originalRole, setOriginalRole] = useState<RoleType | ''>('')
  const [isActive, setIsActive] = useState(true)
  const [selectedProperties, setSelectedProperties] = useState<string[]>([])
  const [selectedDepartments, setSelectedDepartments] = useState<string[]>([])
  const [reportingTo, setReportingTo] = useState<string | null>(null)
  const [staffId, setStaffId] = useState('')

  const [openReportingTo, setOpenReportingTo] = useState(false)
  const [managerSearch, setManagerSearch] = useState('')

  const triggerKeyboardAction = (event: KeyboardEvent<HTMLDivElement>, action: () => void) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      event.stopPropagation()
      action()
    }
  }

  // ... (rest of invalidation)

  const createUserMutation = useMutation({
    mutationFn: async () => {
      if (!email || !fullName || !role) {
        throw new Error(t('form.error.required_fields'))
      }

      // Prepare payload for atomic creation
      // Note: staff_id is auto-generated by database trigger
      const validPropertyIds = selectedProperties.filter((id) => isValidUUID(id))
      const validDepartmentIds = selectedDepartments.filter((id) => isValidUUID(id))
      const payload = {
        email,
        fullName,
        phone: phone || undefined,
        jobTitle: jobTitle || undefined,
        role,
        organizationId: currentOrganization?.id,
        propertyIds: validPropertyIds,
        departmentIds: validDepartmentIds,
        reportingTo: reportingTo && isValidUUID(reportingTo) ? reportingTo : undefined,
      }

      // Call the edge function

      const { data, error: fnError } = await supabase.functions.invoke('create-user', {
        body: payload,
      })

      if (fnError) {
        // Extract the real error message from the edge function response body
        let detailedMessage: string | undefined
        const maybeContext = fnError as unknown as { context?: Response | { response?: Response } }
        const response = maybeContext?.context instanceof Response
          ? maybeContext.context
          : maybeContext?.context?.response
        if (response) {
          try {
            const text = await response.text()
            const parsed = text ? (JSON.parse(text) as { error?: string; details?: unknown }) : null
            detailedMessage = parsed?.error || undefined
          } catch {
            // Response body could not be read/parsed — fall through to generic message
          }
        }

        throw new Error(detailedMessage || fnError.message || 'Failed to create user')
      }

      if (data?.error) {
        throw new Error(data.error)
      }

      const response = (data || {}) as { userId?: string, tempPassword?: string, message?: string }
      if (!response.userId) throw new Error('User ID not returned from create-user function')

      return response
    },
    onSuccess: (response) => {
      // Success - refresh the user list

      const tempPwd = response?.tempPassword

      // Copy password to clipboard automatically
      if (tempPwd) {
        navigator.clipboard.writeText(tempPwd).catch(() => {
          toast({
            title: t('form.error.clipboard_failed', 'Copy failed'),
            description: t('form.error.clipboard_failed_desc', 'Please copy the password manually.'),
            variant: "destructive"
          })
        })
      }

      // Show credentials in a persistent toast - NO auto-download needed
      toast({
        title: t('form.success.created_title'),
        description: (
          <div className="mt-2 space-y-2">
            <p><strong>{t('form.email')}:</strong> {email}</p>
            {tempPwd ? (
              <>
                <p><strong>{tCommon('common.password', 'Password')}:</strong> <code className="bg-gray-100 px-2 py-0.5 rounded">{tempPwd}</code></p>
                <p className="text-xs text-gray-500">{t('form.success.password_copied')}</p>
              </>
            ) : (
              <p className="text-xs text-gray-500">{t('form.success.invite_sent', 'Invitation email sent to the user.')}</p>
            )}
          </div>
        ),
        duration: 30000,
      })

      onClose()
    },
    onError: (error) => {
      const errorDetails = getUserFriendlyError(error)
      toast({
        title: t('form.error.create_failed'),
        description: errorDetails.message,
        variant: "destructive"
      })
    }
  })


  const { data: properties, isLoading: propertiesLoading } = useQuery({
    queryKey: ['properties', 'hotels'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('hotels')
        .select('*')
        .eq('is_active', true)
        .eq('is_deleted', false)
        .order('name')

      if (error) throw error
      return data ?? []
    },
  })

  /* 
    Updated to use useDepartments hook which includes fallback data handling 
    for persistent 400 Bad Request API errors.
  */
  const { departments, isLoading: departmentsLoading } = useDepartments()

  // Fetch Job Titles from DB
  const { data: jobTitlesList, isLoading: jobTitlesLoading } = useQuery({
    queryKey: ['job_titles'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('job_titles')
        .select(`
            *,
            department:departments(id, property_id)
        `)
        .order('title', { ascending: true })

      if (error) throw error
      return data as { id: string; title: string; default_role: AppRole; category: string; department?: { id: string; property_id: string } }[]
    },
  })
  const [openJobTitle, setOpenJobTitle] = useState(false)
  const jobTitleListId = useId()

  // Fetch potential managers based on selected departments/properties
  const { data: potentialManagers } = useQuery({
    queryKey: ['potential-managers', selectedDepartments, selectedProperties],
    queryFn: async () => {
      if (selectedDepartments.length === 0 && selectedProperties.length === 0) return []

      // Fetch profiles with manager-level roles in the selected departments/properties
      const query = supabase
        .from('profiles')
        .select(`
          id,
          full_name,
          job_title,
          staff_id,
          user_roles(role),
          user_departments(department_id),
          user_properties(property_id)
        `)
        .eq('is_active', true)

      const { data, error } = await query
      if (error) throw error

      // Filter to only include people with management roles
      const rows = (data || []) as PotentialManagerRow[]

      return rows
        .filter((p: PotentialManagerRow) => {
          const roles = p.user_roles?.map((r) => r.role) || []
          const hasManagerRole = roles.some((r: string) => MANAGER_ROLES.includes(r))
          if (!hasManagerRole) return false

          // Check if they're in the same department or property
          const deptIds = p.user_departments?.map((d) => d.department_id) || []
          const propIds = p.user_properties?.map((pp) => pp.property_id) || []

          const sameDept = selectedDepartments.some(d => deptIds.includes(d))
          const sameProp = selectedProperties.some(p => propIds.includes(p))

          return sameDept || sameProp
        })
        .map((p: PotentialManagerRow): PotentialManager => ({
          id: p.id,
          full_name: p.full_name,
          job_title: p.job_title,
          staff_id: p.staff_id,
          roles: p.user_roles?.map((r) => r.role) || [],
          isDeptHead: (p.user_roles?.map((r) => r.role) || []).includes('department_head')
        }))
        // Sort: department heads first, then by name
        .sort((a: PotentialManager, b: PotentialManager) => {
          if (a.isDeptHead && !b.isDeptHead) return -1
          if (!a.isDeptHead && b.isDeptHead) return 1
          return a.full_name.localeCompare(b.full_name)
        })
    },
    enabled: selectedDepartments.length > 0 || selectedProperties.length > 0
  })

  const { data: reportingToProfile } = useQuery({
    queryKey: ['manager-profile', reportingTo],
    queryFn: async () => {
      if (!reportingTo) return null
      const { data, error } = await supabase
        .from('profiles')
        .select('id, full_name, job_title, staff_id')
        .eq('id', reportingTo)
        .single()
      if (error) throw error
      return data as { id: string; full_name: string; job_title: string | null; staff_id: string | null }
    },
    enabled: !!reportingTo
  })

  const { data: searchedManagers } = useQuery({
    queryKey: ['manager-search', managerSearch],
    queryFn: async () => {
      const trimmed = managerSearch.trim()
      if (trimmed.length < 2) return []

      const escaped = escapeSearchQuery(trimmed)
      const { data, error } = await supabase
        .from('profiles')
        .select(`
          id,
          full_name,
          job_title,
          staff_id,
          user_roles(role),
          user_departments(department_id),
          user_properties(property_id)
        `)
        .eq('is_active', true)
        .or(`full_name.ilike.%${escaped}%,staff_id.ilike.%${escaped}%,job_title.ilike.%${escaped}%`)
        .limit(20)

      if (error) throw error

      const rows = (data || []) as PotentialManagerRow[]

      return rows
        .filter((p: PotentialManagerRow) => {
          const roles = p.user_roles?.map((r) => r.role) || []
          return roles.some((r: string) => MANAGER_ROLES.includes(r))
        })
        .map((p: PotentialManagerRow): PotentialManager => ({
          id: p.id,
          full_name: p.full_name,
          job_title: p.job_title,
          staff_id: p.staff_id,
          roles: p.user_roles?.map((r) => r.role) || [],
          isDeptHead: (p.user_roles?.map((r) => r.role) || []).includes('department_head')
        }))
        .sort((a: PotentialManager, b: PotentialManager) => a.full_name.localeCompare(b.full_name))
    },
    enabled: managerSearch.trim().length >= 2
  })

  const combinedManagers = useMemo(() => {
    const byId = new Map<string, PotentialManager>()
    ;(potentialManagers || []).forEach((m: PotentialManager) => byId.set(m.id, m))
    ;(searchedManagers || []).forEach((m: PotentialManager) => byId.set(m.id, m))
    if (reportingToProfile && !byId.has(reportingToProfile.id)) {
      byId.set(reportingToProfile.id, {
        id: reportingToProfile.id,
        full_name: reportingToProfile.full_name,
        job_title: reportingToProfile.job_title,
        staff_id: reportingToProfile.staff_id,
        roles: [],
        isDeptHead: false
      })
    }
    return Array.from(byId.values())
  }, [potentialManagers, reportingToProfile, searchedManagers])

  const selectedManager = reportingTo
    ? combinedManagers.find((m) => m.id === reportingTo) || null
    : null

  const loadUserData = useCallback(async () => {
    if (!user) return

    // Load roles
    const { data: rolesData } = await supabase
      .from('user_roles')
      .select('role')
      .eq('user_id', user.id)

    if (rolesData && rolesData.length > 0) {
      setRole(rolesData[0].role)
      setOriginalRole(rolesData[0].role)
    }

    // Load properties / hotels and departments from memberships
    const { data: membershipData } = await supabase
      .from('organization_memberships')
      .select('hotel_id, department_id')
      .eq('user_id', user.id)
      .eq('is_active', true)

    if (membershipData) {
      setSelectedProperties(
        membershipData
          .map((m: any) => m.hotel_id)
          .filter((id): id is string => typeof id === 'string' && isValidUUID(id))
      )
      setSelectedDepartments(
        membershipData
          .map((m: any) => m.department_id)
          .filter((id): id is string => typeof id === 'string' && isValidUUID(id))
      )
    }

    // Load reporting_to
    const { data: profileData } = await supabase
      .from('profiles')
      .select('reporting_to, staff_id')
      .eq('id', user.id)
      .single()

    if (profileData) {
      setReportingTo(profileData.reporting_to)
      setStaffId(profileData.staff_id || '')
    }
  }, [user])

  const hydrateStateFromUser = useCallback((sourceUser: Profile) => {
    setEmail(sourceUser.email)
    setFullName(sourceUser.full_name || '')
    setPhone(sourceUser.phone || '')
    setJobTitle(sourceUser.job_title || '')
    setIsActive(sourceUser.is_active !== false) // Default to true if undefined
    setReportingTo(sourceUser.reporting_to || null)
    setStaffId(sourceUser.staff_id || '')
  }, [])

  useEffect(() => {
    if (user) {
      hydrateStateFromUser(user)
      // Load user's roles, properties, departments
      loadUserData()
    }
  }, [user, loadUserData, hydrateStateFromUser])

  // Auto-suggest manager when department changes (for new users)
  const maybeAutoSuggestManager = useCallback((managers: PotentialManager[] | undefined) => {
    if (user || reportingTo) return
    if (!managers || managers.length === 0) return
    const deptHead = managers.find((m) => m.isDeptHead)
    if (!deptHead) return
    setReportingTo(deptHead.id)
    toast({
      title: t('form.manager_auto_selected'),
      description: t('form.manager_auto_selected_desc', { name: deptHead.full_name, jobTitle: deptHead.job_title || 'Manager' }),
    })
  }, [reportingTo, t, toast, user])

  useEffect(() => {
    maybeAutoSuggestManager(potentialManagers as PotentialManager[] | undefined)
  }, [potentialManagers, maybeAutoSuggestManager])

  // Handle job title selection from DB
  const handleJobTitleSelect = (selectedTitle: string) => {
    setJobTitle(selectedTitle)
    setOpenJobTitle(false)

    // Find the corresponding job title object to get the role
    const titleObj = jobTitlesList?.find(t => t.title === selectedTitle)

    if (titleObj) {
      // Auto-select Role
      setRole(titleObj.default_role)

      let targetDeptId: string | undefined = titleObj.department?.id
      let targetPropertyId: string | undefined = titleObj.department?.property_id

      // Fallback: If no direct link, try to match by Category Name
      if (!targetDeptId && titleObj.category && departments) {
        // Try to find a department with matching name
        // 1. Prefer department in already selected properties
        let match = departments.find(d =>
          d.name === titleObj.category && selectedProperties.includes(d.property_id)
        )
        // 2. If not found, just pick the first one matching the name
        if (!match) {
          match = departments.find(d => d.name === titleObj.category)
        }

        if (match) {
          targetDeptId = match.id
          targetPropertyId = match.property_id
        }
      }

      // Auto-select Department & Property
      if (targetDeptId && targetPropertyId) {
        // Add property if not already selected
        if (!selectedProperties.includes(targetPropertyId)) {
          setSelectedProperties(prev => [...prev, targetPropertyId!])
        }

        // Add department if not already selected
        if (!selectedDepartments.includes(targetDeptId)) {
          setSelectedDepartments(prev => [...prev, targetDeptId!])
        }

        toast({
          title: t('form.success.auto_assigned'),
          description: t('form.success.auto_assigned_desc'),
        })
      }
    }
  }



  const updateUserMutation = useMutation({
    mutationFn: async () => {
      if (!user) return

      // Update profile with job title, active status, and reporting_to
      // Note: staff_id is NOT updated - it's auto-generated and read-only
      const { error: profileError } = await supabase
        .from('profiles')
        .update({
          full_name: fullName,
          phone: phone || null,
          job_title: jobTitle || null,
          is_active: isActive,
          reporting_to: reportingTo && isValidUUID(reportingTo) ? reportingTo : null,
        })
        .eq('id', user.id)

      if (profileError) throw profileError

      // Update role (insert-first, then cleanup stale roles).
      // This avoids leaving the user with no role if insertion fails.
      if (role) {
        const { error: upsertRoleErr } = await supabase
          .from('user_roles')
          .upsert({ user_id: user.id, role }, { onConflict: 'user_id,role', ignoreDuplicates: true })
        if (upsertRoleErr) throw upsertRoleErr

        const { error: cleanupRoleErr } = await supabase
          .from('user_roles')
          .delete()
          .eq('user_id', user.id)
          .neq('role', role)
        if (cleanupRoleErr) throw cleanupRoleErr
      }

      // Update organization memberships (hotel and department scope)
      const primaryHotelId = selectedProperties.find((id) => isValidUUID(id)) || null
      const primaryDeptId = selectedDepartments.find((id) => isValidUUID(id)) || null
      const tenantRole = role === 'administrator' || role === 'corporate_admin' || role === 'super_admin'
        ? 'organization_admin'
        : role === 'training_manager'
        ? 'training_manager'
        : role === 'property_manager'
        ? 'hotel_admin'
        : role === 'department_head'
        ? 'department_manager'
        : 'learner'

      const targetOrgId = user?.organization_id || currentOrganization?.id
      if (targetOrgId) {
        await supabase
          .from('organization_memberships')
          .upsert({
            user_id: user.id,
            organization_id: targetOrgId,
            hotel_id: primaryHotelId,
            department_id: primaryDeptId,
            role: tenantRole as any,
            is_active: true,
            is_primary: true,
            updated_at: new Date().toISOString()
          }, { onConflict: 'organization_id,user_id' })
      }
    },
    onSuccess: () => {
      toast({
        title: t('form.success.updated_title', { defaultValue: 'User Updated' }),
        description: t('form.success.updated_message', { defaultValue: 'User information has been updated successfully.' })
      })

      if (user && originalRole && role && originalRole !== role) {
        setOriginalRole(role)
      }

      onClose()
    },
    onError: (error) => {
      const errorDetails = getUserFriendlyError(error)
      toast({
        title: t('form.error.update_failed', { defaultValue: 'Update Failed' }),
        description: errorDetails.message,
        variant: 'destructive'
      })
    }
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    // Validate form data
    try {
      const validPropertyIds = selectedProperties.filter((id) => isValidUUID(id))
      const validDepartmentIds = selectedDepartments.filter((id) => isValidUUID(id))
      const validReportingTo = reportingTo && isValidUUID(reportingTo) ? reportingTo : undefined
      const formData: UserFormData = {
        email,
        full_name: fullName,
        phone: phone || undefined,
        job_title: jobTitle || undefined,
        role: role as UserFormData['role'],
        property_ids: validPropertyIds,
        department_ids: validDepartmentIds,
        reporting_to: validReportingTo,
        is_active: isActive,
        hire_date: undefined,
        staff_id: undefined
      }

      // Validate using Zod schema
      userSchema.parse(formData)

      // If validation passes, proceed with mutation
      if (user) {
        updateUserMutation.mutate()
      } else {
        createUserMutation.mutate()
      }
    } catch (error) {
      // Handle validation errors
      if (error instanceof ZodError) {
        const firstIssue = error.issues[0]
        toast({
          title: t('form.error.validation_failed'),
          description: firstIssue?.message || tCommon('errors:validation_error'),
          variant: 'destructive'
        })
        return
      }

      const errorDetails = getUserFriendlyError(error)
      toast({
        title: t('form.error.validation_failed'),
        description: errorDetails.message,
        variant: 'destructive'
      })
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title={user ? t('form.edit_user') : t('form.create_user')}
        actions={
          <Button variant="ghost" onClick={onClose}>
            <ArrowLeft className="w-4 h-4 me-2" />
            {tCommon('common.back')}
          </Button>
        }
      />

      <Card>
        <CardHeader>
          <CardTitle>{t('form.user_info')}</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="email">{t('form.email')}</Label>
                <Input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  disabled={!!user}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="fullName">{t('form.full_name')}</Label>
                <Input
                  id="fullName"
                  value={fullName}
                  onChange={(e) => setFullName(e.target.value)}
                  required
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="staffId">
                  {t('form.staff_id', 'Staff ID / Employee Code')}
                </Label>
                {user ? (
                  <div className="flex items-center h-10 px-3 rounded-md border bg-muted/50 font-mono text-sm">
                    {staffId || <span className="text-muted-foreground italic">Not assigned</span>}
                  </div>
                ) : (
                  <div className="flex items-center h-10 px-3 rounded-md border border-dashed bg-green-50 text-green-700 text-sm">
                    <span className="me-2">✨</span>
                    {t('form.staff_id_auto', 'Auto-generated on creation')}
                  </div>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="phone">{t('form.phone')}</Label>
                <Input
                  id="phone"
                  type="tel"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="jobTitle">{t('form.job_title')} *</Label>
              <Popover open={openJobTitle} onOpenChange={setOpenJobTitle}>
                <PopoverTrigger asChild>
                  <Button
                    type="button"
                    variant="outline"
                    role="combobox"
                    aria-expanded={openJobTitle}
                    aria-controls={jobTitleListId}
                    className="w-full justify-between font-normal text-left"
                  >
                    {jobTitle || t('form.select_job_title')}
                    <ChevronsUpDown className="ms-2 h-4 w-4 shrink-0 opacity-50" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-[400px] p-0" align="start">
                  <Command>
                    <CommandInput placeholder={t('form.search_job_title')} />
                    <CommandList id={jobTitleListId}>
                      <CommandEmpty>
                        {jobTitlesLoading ? t('form.loading_job_titles', 'Loading job titles...') : t('form.no_job_title')}
                      </CommandEmpty>
                      <CommandGroup>
                        {jobTitlesList?.map((item) => (
                          <CommandItem
                            key={item.id}
                            value={item.title}
                            onSelect={() => {
                              handleJobTitleSelect(item.title)
                            }}
                            className="p-0 data-[disabled]:pointer-events-auto data-[disabled]:opacity-100"
                          >
                            <div
                              className="w-full flex items-center px-2 py-1.5 cursor-pointer"
                              onPointerDown={(e) => {
                                e.preventDefault()
                              }}
                              onClick={(e) => {
                                e.stopPropagation()
                                handleJobTitleSelect(item.title)
                              }}
                              onKeyDown={(e) => triggerKeyboardAction(e, () => handleJobTitleSelect(item.title))}
                              role="button"
                              tabIndex={0}
                              aria-label={t('form.select_job_title')}
                            >
                              <Check
                                className={cn(
                                  "me-2 h-4 w-4",
                                  jobTitle === item.title ? "opacity-100" : "opacity-0"
                                )}
                              />
                              {item.title} <span className="ms-auto text-xs text-muted-foreground">{item.category}</span>
                            </div>
                          </CommandItem>
                        ))}
                      </CommandGroup>
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
              <p className="text-xs text-muted-foreground">
                {t('form.job_title_helper')}
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="role">{t('form.permission_level')} *</Label>
              <select
                id="role"
                value={role}
                onChange={(e) => setRole(e.target.value as RoleType)}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                required
              >
                <option value="">{t('form.select_role')}</option>
                {ROLE_HIERARCHY.map((r) => (
                  <option key={r} value={r}>
                    {tCommon(`roles.${r}`, ROLES[r].label)}
                  </option>
                ))}
              </select>
              <p className="text-xs text-muted-foreground">
                {t('form.role_helper')}
              </p>
            </div>

            {/* User Status Toggle - Only show for existing users */}
            {user && (
              <div className="flex items-center justify-between p-4 border rounded-lg bg-muted/50">
                <div className="space-y-0.5">
                  <Label htmlFor="is-active" className="font-medium">{t('form.account_status')}</Label>
                  <p className="text-sm text-muted-foreground">
                    {isActive
                      ? t('form.status_active_helper')
                      : t('form.status_inactive_helper')}
                  </p>
                </div>
                <Switch
                  id="is-active"
                  checked={isActive}
                  onCheckedChange={setIsActive}
                />
              </div>
            )}

            <div className="space-y-2">
              <Label>{t('form.properties')}</Label>
              <div className="grid grid-cols-2 gap-2 max-h-40 overflow-y-auto border rounded-md p-2">
                {propertiesLoading ? (
                  <p className="text-sm text-muted-foreground">{t('form.loading_properties', 'Loading properties...')}</p>
                ) : properties?.map((property) => (
                  <label key={property.id} className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={selectedProperties.includes(property.id)}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setSelectedProperties([...selectedProperties, property.id])
                        } else {
                          setSelectedProperties(selectedProperties.filter((id) => id !== property.id))
                        }
                      }}
                    />
                    <span className="text-sm">{property.name}</span>
                  </label>
                ))}
              </div>
            </div>

            <div className="space-y-4">
              <Label>{t('form.departments')}</Label>
              <div className="max-h-60 overflow-y-auto border rounded-md p-4 space-y-4">
                {selectedProperties.length > 0 ? (
                  departmentsLoading ? (
                    <p className="text-sm text-muted-foreground text-center py-4">{t('form.loading_departments', 'Loading departments...')}</p>
                  ) : (
                  properties?.filter(p => selectedProperties.includes(p.id)).map((property) => {
                    const propertyDepts = departments?.filter(d => d.property_id === property.id)

                    if (!propertyDepts || propertyDepts.length === 0) return null

                    return (
                      <div key={property.id} className="space-y-2">
                        <h4 className="text-sm font-semibold font-sans text-gray-900 sticky top-0 bg-background py-1 border-b flex items-center gap-2">
                          <span className="w-1.5 h-1.5 rounded-full bg-hotel-gold"></span>
                          {property.name}
                        </h4>
                        <div className="grid grid-cols-2 gap-2">
                          {propertyDepts.map((department) => (
                            <label key={department.id} className="flex items-center gap-2 cursor-pointer hover:bg-muted p-1 rounded">
                              <input
                                type="checkbox"
                                className="rounded border-gray-300 text-hotel-gold focus:ring-hotel-gold"
                                checked={selectedDepartments.includes(department.id)}
                                onChange={(e) => {
                                  if (e.target.checked) {
                                    setSelectedDepartments([...selectedDepartments, department.id])
                                  } else {
                                    setSelectedDepartments(selectedDepartments.filter((id) => id !== department.id))
                                  }
                                }}
                              />
                              <span className="text-sm text-muted-foreground">{department.name}</span>
                            </label>
                          ))}
                        </div>
                      </div>
                    )
                  })
                  )
                ) : (
                  <div className="text-sm text-muted-foreground text-center py-8 bg-muted/50 rounded-lg flex flex-col items-center justify-center border border-dashed">
                    <span className="mb-1 text-2xl">🏢</span>
                    <p>{t('form.select_property_helper')}</p>
                  </div>
                )}
                {selectedProperties.length > 0 && !departmentsLoading && (!departments || departments.length === 0) && (
                  <p className="text-sm text-muted-foreground text-center py-4">{t('form.no_departments')}</p>
                )}
              </div>
            </div>

            {/* Reports To (Manager) */}
            <div className="space-y-2">
              <Label htmlFor="reportingTo">{t('form.reports_to')}</Label>
              <Popover open={openReportingTo} onOpenChange={setOpenReportingTo}>
                <PopoverTrigger asChild>
                  <Button
                    type="button"
                    variant="outline"
                    role="combobox"
                    aria-expanded={openReportingTo}
                    aria-controls={managerListId}
                    className="w-full justify-between font-normal text-left"
                  >
                    {reportingTo
                      ? selectedManager?.full_name || reportingToProfile?.full_name || t('form.selected_manager')
                      : t('form.select_manager')}
                    <ChevronsUpDown className="ms-2 h-4 w-4 shrink-0 opacity-50" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-[400px] p-0" align="start">
                  <Command>
                    <CommandInput
                      placeholder={t('form.search_managers')}
                      value={managerSearch}
                      onValueChange={setManagerSearch}
                    />
                    <CommandList id={managerListId}>
                      <CommandEmpty>
                        {managerSearch.trim().length >= 2
                          ? t('form.manager_none_helper')
                          : selectedDepartments.length === 0 && selectedProperties.length === 0
                            ? t('form.manager_dept_helper')
                            : t('form.manager_none_helper')
                        }
                      </CommandEmpty>
                      <CommandGroup heading={t('form.available_managers')}>
                        <CommandItem
                          value="no-manager"
                          onSelect={() => {
                            setReportingTo(null)
                            setManagerSearch('')
                            setOpenReportingTo(false)
                          }}
                          className="p-0 data-[disabled]:pointer-events-auto data-[disabled]:opacity-100"
                        >
                          <div
                            className="w-full flex items-center px-2 py-1.5 cursor-pointer"
                            onPointerDown={(e) => e.preventDefault()}
                            onClick={(e) => {
                              e.stopPropagation()
                              setReportingTo(null)
                              setManagerSearch('')
                              setOpenReportingTo(false)
                            }}
                            onKeyDown={(e) => triggerKeyboardAction(e, () => {
                              setReportingTo(null)
                              setManagerSearch('')
                              setOpenReportingTo(false)
                            })}
                            role="button"
                            tabIndex={0}
                            aria-label={t('form.no_manager_top')}
                          >
                            <Check
                              className={cn(
                                "me-2 h-4 w-4",
                                !reportingTo ? "opacity-100" : "opacity-0"
                              )}
                            />
                            <span className="text-muted-foreground">{t('form.no_manager_top')}</span>
                          </div>
                        </CommandItem>
                        {potentialManagers?.map((manager: PotentialManager) => (
                          <CommandItem
                            key={manager.id}
                            value={`${manager.full_name} ${manager.staff_id || ''} ${manager.job_title || ''}`}
                            onSelect={() => {
                              setReportingTo(manager.id)
                              setManagerSearch('')
                              setOpenReportingTo(false)
                            }}
                            className="p-0 data-[disabled]:pointer-events-auto data-[disabled]:opacity-100"
                          >
                            <div
                              className="w-full flex items-center px-2 py-1.5 cursor-pointer"
                              onPointerDown={(e) => e.preventDefault()}
                              onClick={(e) => {
                                e.stopPropagation()
                                setReportingTo(manager.id)
                                setManagerSearch('')
                                setOpenReportingTo(false)
                              }}
                              onKeyDown={(e) => triggerKeyboardAction(e, () => {
                                setReportingTo(manager.id)
                                setManagerSearch('')
                                setOpenReportingTo(false)
                              })}
                              role="button"
                              tabIndex={0}
                              aria-label={t('form.select_manager')}
                            >
                              <Check
                                className={cn(
                                  "me-2 h-4 w-4",
                                  reportingTo === manager.id ? "opacity-100" : "opacity-0"
                                )}
                              />
                              <span>{manager.full_name}</span>
                              <span className="ms-2 text-[10px] bg-slate-100 px-1 rounded text-slate-500 font-mono">
                                {manager.staff_id || 'no-id'}
                              </span>
                              <span className="ms-auto text-xs text-muted-foreground">
                                {manager.job_title || manager.roles?.join(', ')}
                              </span>
                              {manager.isDeptHead && (
                                <span className="ms-2 text-xs bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded">
                                  {t('form.dept_head')}
                                </span>
                              )}
                            </div>
                          </CommandItem>
                        ))}
                      </CommandGroup>
                      {managerSearch.trim().length >= 2 && (searchedManagers?.length || 0) > 0 && (
                        <CommandGroup heading={t('form.search_results', 'Search Results')}>
                          {searchedManagers
                            ?.filter((manager: PotentialManager) => !potentialManagers?.some((m) => m.id === manager.id))
                            .map((manager: PotentialManager) => (
                              <CommandItem
                                key={manager.id}
                                value={`${manager.full_name} ${manager.staff_id || ''} ${manager.job_title || ''}`}
                                onSelect={() => {
                                  setReportingTo(manager.id)
                                  setManagerSearch('')
                                  setOpenReportingTo(false)
                                }}
                                className="p-0 data-[disabled]:pointer-events-auto data-[disabled]:opacity-100"
                              >
                                <div
                                  className="w-full flex items-center px-2 py-1.5 cursor-pointer"
                                  onPointerDown={(e) => e.preventDefault()}
                                  onClick={(e) => {
                                    e.stopPropagation()
                                    setReportingTo(manager.id)
                                    setManagerSearch('')
                                    setOpenReportingTo(false)
                                  }}
                                  onKeyDown={(e) => triggerKeyboardAction(e, () => {
                                    setReportingTo(manager.id)
                                    setManagerSearch('')
                                    setOpenReportingTo(false)
                                  })}
                                  role="button"
                                  tabIndex={0}
                                  aria-label={t('form.select_manager')}
                                >
                                  <Check
                                    className={cn(
                                      "me-2 h-4 w-4",
                                      reportingTo === manager.id ? "opacity-100" : "opacity-0"
                                    )}
                                  />
                                  <span>{manager.full_name}</span>
                                  <span className="ms-2 text-[10px] bg-slate-100 px-1 rounded text-slate-500 font-mono">
                                    {manager.staff_id || 'no-id'}
                                  </span>
                                  <span className="ms-auto text-xs text-muted-foreground">
                                    {manager.job_title || manager.roles?.join(', ')}
                                  </span>
                                </div>
                              </CommandItem>
                            ))}
                        </CommandGroup>
                      )}
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
              <p className="text-xs text-muted-foreground">
                {selectedDepartments.length === 0 && selectedProperties.length === 0
                  ? t('form.suggested_manager_helper')
                  : reportingTo
                    ? t('form.auto_suggested_helper')
                    : t('form.top_level_helper')}
              </p>
            </div>

            <div className="flex justify-end gap-2">
              <Button type="button" variant="outline" onClick={onClose}>
                {tCommon('common.cancel')}
              </Button>
              <LoadingButton
                type="submit"
                className="bg-hotel-gold text-white hover:bg-hotel-gold-dark rounded-md transition-colors"
                loading={createUserMutation.isPending || updateUserMutation.isPending}
                loadingText={user ? tCommon('common.updating') : tCommon('common.creating')}
              >
                {user ? tCommon('common.update') : tCommon('common.create')} {t('user')}
              </LoadingButton>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
