-- Generated DROP statements
DROP POLICY IF EXISTS "Admins can view all PII logs" ON public.pii_access_logs;
DROP POLICY IF EXISTS "Anyone can view quiz questions" ON public.quiz_questions;
DROP POLICY IF EXISTS "Anyone can view running quizzes" ON public.quizzes;
DROP POLICY IF EXISTS "Authenticated can manage questions" ON public.quiz_questions;
DROP POLICY IF EXISTS "Authenticated can view goals" ON public.goals;
DROP POLICY IF EXISTS "Authenticated can view payslips" ON public.payslips;
DROP POLICY IF EXISTS "Managers can create shifts" ON public.shifts;
DROP POLICY IF EXISTS "Managers can delete shifts" ON public.shifts;
DROP POLICY IF EXISTS "Managers can update leave requests" ON public.leave_requests;
DROP POLICY IF EXISTS "Published SOPs are viewable by all authenticated users" ON public.sop_documents;
DROP POLICY IF EXISTS "Update own shifts" ON public.shifts;
DROP POLICY IF EXISTS "Users can acknowledge announcements" ON public.announcement_acknowledgments;
DROP POLICY IF EXISTS "Users can create leave requests" ON public.leave_requests;
DROP POLICY IF EXISTS "Users can create own answers" ON public.quiz_answers;
DROP POLICY IF EXISTS "Users can create own attempts" ON public.quiz_attempts;
DROP POLICY IF EXISTS "Users can delete own acknowledgment" ON public.announcement_acknowledgments;
DROP POLICY IF EXISTS "Users can update own attempts" ON public.quiz_attempts;
DROP POLICY IF EXISTS "Users can view acknowledgments" ON public.announcement_acknowledgments;
DROP POLICY IF EXISTS "Users can view own acknowledgments" ON public.announcement_acknowledgments;
DROP POLICY IF EXISTS "Users can view own answers" ON public.quiz_answers;
DROP POLICY IF EXISTS "Users can view own attempts" ON public.quiz_attempts;
DROP POLICY IF EXISTS "announcements_manage_policy" ON public.announcements;
DROP POLICY IF EXISTS "announcements_select_policy" ON public.announcements;
DROP POLICY IF EXISTS "attendance_all" ON public.attendance;
DROP POLICY IF EXISTS "attendance_insert_admin" ON public.attendance;
DROP POLICY IF EXISTS "attendance_insert_own" ON public.attendance;
DROP POLICY IF EXISTS "attendance_manage_policy" ON public.attendance;
DROP POLICY IF EXISTS "attendance_select_admin" ON public.attendance;
DROP POLICY IF EXISTS "attendance_select_policy" ON public.attendance;
DROP POLICY IF EXISTS "attendance_update_admin" ON public.attendance;
DROP POLICY IF EXISTS "attendance_update_own" ON public.attendance;
DROP POLICY IF EXISTS "consolidated_attendance_select" ON public.attendance;
DROP POLICY IF EXISTS "consolidated_leave_requests_select" ON public.leave_requests;
DROP POLICY IF EXISTS "consolidated_performance_reviews_select" ON public.performance_reviews;
DROP POLICY IF EXISTS "consolidated_pii_access_logs_select" ON public.pii_access_logs;
DROP POLICY IF EXISTS "consolidated_profiles_all" ON public.profiles;
DROP POLICY IF EXISTS "consolidated_profiles_select" ON public.profiles;
DROP POLICY IF EXISTS "consolidated_shifts_select" ON public.shifts;
DROP POLICY IF EXISTS "consolidated_sop_documents_all" ON public.sop_documents;
DROP POLICY IF EXISTS "consolidated_user_departments_all" ON public.user_departments;
DROP POLICY IF EXISTS "consolidated_user_departments_select" ON public.user_departments;
DROP POLICY IF EXISTS "consolidated_user_properties_all" ON public.user_properties;
DROP POLICY IF EXISTS "consolidated_user_properties_select" ON public.user_properties;
DROP POLICY IF EXISTS "consolidated_user_roles_all" ON public.user_roles;
DROP POLICY IF EXISTS "consolidated_user_roles_select" ON public.user_roles;
DROP POLICY IF EXISTS "employee_reviews_view_own" ON public.performance_reviews;
DROP POLICY IF EXISTS "goals_insert_admin" ON public.goals;
DROP POLICY IF EXISTS "goals_insert_own" ON public.goals;
DROP POLICY IF EXISTS "goals_select_admin" ON public.goals;
DROP POLICY IF EXISTS "goals_select_own" ON public.goals;
DROP POLICY IF EXISTS "goals_update_admin" ON public.goals;
DROP POLICY IF EXISTS "goals_update_own" ON public.goals;
DROP POLICY IF EXISTS "learning_assignments_manage_policy" ON public.learning_assignments;
DROP POLICY IF EXISTS "learning_assignments_select_policy" ON public.learning_assignments;
DROP POLICY IF EXISTS "learning_progress_manage_policy" ON public.learning_progress;
DROP POLICY IF EXISTS "learning_progress_select_policy" ON public.learning_progress;
DROP POLICY IF EXISTS "leave_requests_insert_policy" ON public.leave_requests;
DROP POLICY IF EXISTS "leave_requests_manage_policy" ON public.leave_requests;
DROP POLICY IF EXISTS "leave_requests_select_policy" ON public.leave_requests;
DROP POLICY IF EXISTS "payslips_insert_admin" ON public.payslips;
DROP POLICY IF EXISTS "payslips_select_admin" ON public.payslips;
DROP POLICY IF EXISTS "payslips_select_own" ON public.payslips;
DROP POLICY IF EXISTS "payslips_update_admin" ON public.payslips;
DROP POLICY IF EXISTS "performance_reviews_insert_admin" ON public.performance_reviews;
DROP POLICY IF EXISTS "performance_reviews_select_admin" ON public.performance_reviews;
DROP POLICY IF EXISTS "performance_reviews_update_admin" ON public.performance_reviews;
DROP POLICY IF EXISTS "pii_access_logs_insert_admin" ON public.pii_access_logs;
DROP POLICY IF EXISTS "pii_access_logs_select_policy" ON public.pii_access_logs;
DROP POLICY IF EXISTS "profiles_manage_policy" ON public.profiles;
DROP POLICY IF EXISTS "profiles_select_policy" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_policy" ON public.profiles;
DROP POLICY IF EXISTS "quiz_answers_insert" ON public.quiz_answers;
DROP POLICY IF EXISTS "quiz_answers_insert_policy" ON public.quiz_answers;
DROP POLICY IF EXISTS "quiz_answers_select" ON public.quiz_answers;
DROP POLICY IF EXISTS "quiz_answers_select_policy" ON public.quiz_answers;
DROP POLICY IF EXISTS "quiz_attempts_insert" ON public.quiz_attempts;
DROP POLICY IF EXISTS "quiz_attempts_insert_policy" ON public.quiz_attempts;
DROP POLICY IF EXISTS "quiz_attempts_select" ON public.quiz_attempts;
DROP POLICY IF EXISTS "quiz_attempts_select_policy" ON public.quiz_attempts;
DROP POLICY IF EXISTS "quiz_questions_all" ON public.quiz_questions;
DROP POLICY IF EXISTS "quiz_questions_manage_policy" ON public.quiz_questions;
DROP POLICY IF EXISTS "quiz_questions_select_policy" ON public.quiz_questions;
DROP POLICY IF EXISTS "quizzes_all" ON public.quizzes;
DROP POLICY IF EXISTS "quizzes_manage_policy" ON public.quizzes;
DROP POLICY IF EXISTS "quizzes_select_policy" ON public.quizzes;
DROP POLICY IF EXISTS "shifts_admin_manage" ON public.shifts;
DROP POLICY IF EXISTS "shifts_all" ON public.shifts;
DROP POLICY IF EXISTS "sop_documents_manage_policy" ON public.sop_documents;
DROP POLICY IF EXISTS "sop_documents_select_policy" ON public.sop_documents;
DROP POLICY IF EXISTS "tasks_manage_policy" ON public.tasks;
DROP POLICY IF EXISTS "tasks_select_policy" ON public.tasks;
DROP POLICY IF EXISTS "user_properties_manage_policy" ON public.user_properties;
DROP POLICY IF EXISTS "user_properties_select_policy" ON public.user_properties;
DROP POLICY IF EXISTS "user_roles_manage_policy" ON public.user_roles;
DROP POLICY IF EXISTS "user_roles_select_policy" ON public.user_roles;
