REVOKE EXECUTE ON FUNCTION public.delete_operations_import(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.execute_scheduled_report(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_analytics_summary() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_daily_active_users(integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_search_metrics(integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_secure_document_version_url(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_secure_expense_receipt_url(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_secure_maintenance_attachment_url(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_secure_report_run_url(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.replace_workflow_steps(uuid, jsonb) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.delete_operations_import(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.execute_scheduled_report(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_analytics_summary() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_daily_active_users(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_search_metrics(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_secure_document_version_url(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_secure_expense_receipt_url(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_secure_maintenance_attachment_url(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_secure_report_run_url(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.replace_workflow_steps(uuid, jsonb) TO authenticated, service_role;
